language: ruby

rvm:
  - 1.9.3-p484

before_install: ci/scripts/before_install.sh
before_script:  ci/scripts/before_script.sh
script:         ci/scripts/script.sh
after_script:   ci/scripts/after_script.sh
