sudo: required

dist: xenial

language: ruby

cache:
  bundler: true

rvm:
  - 2.6.0

node_js:
  - "10.13.0"

jdk:
  - openjdk8

env:
  global:
    - PGUSER=travis
    - PGHOST=""
    - PGPORT=5433

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - sudo apt-get -qq update
  - curl 'https://www.postgresql.org/media/keys/ACCC4CF8.asc' | sudo apt-key add
  - echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg 11" | sudo tee -a /etc/apt/sources.list.d/postgres-11.list
  - sudo apt-get update
  - sudo apt-get remove --purge -y postgresql-common postgresql-client-common postgresql-9.2 postgresql-client-9.2 postgresql-9.3 postgresql-client-9.3 postgresql-9.4 postgresql-client-9.4 postgresql-9.5 postgresql-client-9.5 postgresql-9.6 postgresql-client-9.6
  - sudo apt-cache search postgis
  - sudo apt-get install -y postgresql-11 postgresql-client-11 postgresql-11-postgis-2.5 libpq-dev
  - sudo apt-get install -y gdal-bin proj-bin libgeos-dev libgeos++-dev libproj-dev
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo cat /etc/postgresql/11/main/postgresql.conf
  - sudo cat /etc/postgresql/11/main/pg_hba.conf
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -c 'create extension "uuid-ossp"'
  - createdb -O postgres template_postgis
  - psql -U postgres template_postgis -c "UPDATE pg_database SET datistemplate = TRUE WHERE datname = 'template_postgis'"
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.4.deb && sudo dpkg -i --force-confnew elasticsearch-5.6.4.deb
  - export JAVA_HOME='/usr'
  - sudo cat /usr/share/elasticsearch/bin/elasticsearch-plugin
  - sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-kuromoji
  - sudo service elasticsearch start
  - gem install bundler
  - mkdir -p tmp/pids
  - echo -e "--format documentation\n--color\n--require spec_helper\n--profile\n--tty" > .rspec

before_script:
  - sleep 15
  - ci/scripts/before_script.sh

env:
  - TRAVIS_CI=true TESTFOLDER=spec/models/*(observation|taxon)_spec.rb
  - TRAVIS_CI=true TESTFOLDER=spec/models/!(observation|taxon)_spec.rb
  - TRAVIS_CI=true TESTFOLDER='spec/controllers spec/helpers spec/initializers spec/lib spec/views'

script: "bundle exec rspec $TESTFOLDER"

notifications:
  slack:
    secure: a5oKH3x+irU27B+5f9hZPLEKl4gFPjj74UXPvVPKJdJ8shnDVwZkJdzsCV9u2qirD07TzZNCKGprTIG4zWJdYyMVmKucwT7hRMPCGIBu/2cGvSBfOSyiDHLNmvUvA6yOaECWT7h8CpTE2wqxNV8avqGlc20oNrxlJT2bpVTTU4U=
